// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Coevery.CodeGeneration.CodeGenerationTemplates
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\Shinetech\Coevery-Framework-V1\src\Coevery.Web\Modules\Coevery.CodeGeneration\CodeGenerationTemplates\ModuleTestsCsProj.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class ModuleTestsCsProj : ModuleTestsCsProjBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"<?xml version=""1.0"" encoding=""utf-8""?>
<Project ToolsVersion=""4.0"" DefaultTargets=""Build"" xmlns=""http://schemas.microsoft.com/developer/msbuild/2003"">
  <Import Project=""$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props"" Condition=""Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')"" />
  <PropertyGroup>
    <Configuration Condition="" '$(Configuration)' == '' "">Debug</Configuration>
    <Platform Condition="" '$(Platform)' == '' "">AnyCPU</Platform>
    <ProjectGuid>{");
            
            #line 13 "F:\Shinetech\Coevery-Framework-V1\src\Coevery.Web\Modules\Coevery.CodeGeneration\CodeGenerationTemplates\ModuleTestsCsProj.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TestsProjectGuid));
            
            #line default
            #line hidden
            this.Write("}</ProjectGuid>\r\n    <OutputType>Library</OutputType>\r\n    <AppDesignerFolder>Pro" +
                    "perties</AppDesignerFolder>\r\n    <RootNamespace>");
            
            #line 16 "F:\Shinetech\Coevery-Framework-V1\src\Coevery.Web\Modules\Coevery.CodeGeneration\CodeGenerationTemplates\ModuleTestsCsProj.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ProjectName));
            
            #line default
            #line hidden
            this.Write("</RootNamespace>\r\n    <AssemblyName>");
            
            #line 17 "F:\Shinetech\Coevery-Framework-V1\src\Coevery.Web\Modules\Coevery.CodeGeneration\CodeGenerationTemplates\ModuleTestsCsProj.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ProjectName));
            
            #line default
            #line hidden
            this.Write("</AssemblyName>\r\n    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>\r\n    <" +
                    "OldToolsVersion>4.0</OldToolsVersion>\r\n  </PropertyGroup>\r\n  <PropertyGroup Cond" +
                    "ition=\" \'$(Configuration)|$(Platform)\' == \'Debug|AnyCPU\' \">\r\n    <DebugSymbols>t" +
                    "rue</DebugSymbols>\r\n    <DebugType>full</DebugType>\r\n    <Optimize>false</Optimi" +
                    "ze>\r\n    <OutputPath>bin\\</OutputPath>\r\n    <DefineConstants>DEBUG;TRACE</Define" +
                    "Constants>\r\n    <ErrorReport>prompt</ErrorReport>\r\n    <WarningLevel>4</WarningL" +
                    "evel>\r\n    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>\r\n    <Pre" +
                    "fer32Bit>false</Prefer32Bit>\r\n  </PropertyGroup>\r\n  <PropertyGroup Condition=\" \'" +
                    "$(Configuration)|$(Platform)\' == \'Release|AnyCPU\' \">\r\n    <DebugType>pdbonly</De" +
                    "bugType>\r\n    <Optimize>true</Optimize>\r\n    <OutputPath>bin\\</OutputPath>\r\n    " +
                    "<DefineConstants>TRACE</DefineConstants>\r\n    <ErrorReport>prompt</ErrorReport>\r" +
                    "\n    <WarningLevel>4</WarningLevel>\r\n    <CodeAnalysisRuleSet>AllRules.ruleset</" +
                    "CodeAnalysisRuleSet>\r\n    <Prefer32Bit>false</Prefer32Bit>\r\n  </PropertyGroup>\r\n" +
                    "  <ItemGroup>\r\n    <Reference Include=\"Autofac\">\r\n      <HintPath>..\\..\\..\\..\\.." +
                    "\\lib\\autofac\\Autofac.dll</HintPath>\r\n    </Reference>\r\n    <Reference Include=\"M" +
                    "oq\">\r\n      <HintPath>..\\..\\..\\..\\..\\lib\\moq\\Moq.dll</HintPath>\r\n    </Reference" +
                    ">\r\n    <Reference Include=\"NHibernate\">\r\n      <HintPath>..\\..\\..\\..\\..\\lib\\nhib" +
                    "ernate\\NHibernate.dll</HintPath>\r\n    </Reference>\r\n    <Reference Include=\"nuni" +
                    "t.framework\">\r\n      <HintPath>..\\..\\..\\..\\..\\lib\\nunit\\nunit.framework.dll</Hin" +
                    "tPath>\r\n    </Reference>\r\n    <Reference Include=\"System\" />\r\n    <Reference Inc" +
                    "lude=\"System.Core\" />\r\n    <Reference Include=\"Microsoft.CSharp\" />\r\n    <Refere" +
                    "nce Include=\"System.Data\" />\r\n    <Reference Include=\"System.Data.SqlServerCe, V" +
                    "ersion=4.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91, processorArchi" +
                    "tecture=MSIL\">\r\n      <SpecificVersion>False</SpecificVersion>\r\n      <HintPath>" +
                    "..\\..\\..\\..\\..\\lib\\sqlce\\System.Data.SqlServerCe.dll</HintPath>\r\n      <Private>" +
                    "True</Private>\r\n    </Reference>\r\n  </ItemGroup>\r\n  ");
            
            #line 65 "F:\Shinetech\Coevery-Framework-V1\src\Coevery.Web\Modules\Coevery.CodeGeneration\CodeGenerationTemplates\ModuleTestsCsProj.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FileIncludes));
            
            #line default
            #line hidden
            this.Write(@"
  <ItemGroup>
    <ProjectReference Include=""..\..\..\..\Coevery.Tests.Modules\Coevery.Tests.Modules.csproj"">
        <Project>{6CB3EB30-F725-45C0-9742-42599BA8E8D2}</Project>
        <Name>Coevery.Tests.Modules</Name>
    </ProjectReference>
    <ProjectReference Include=""..\..\..\..\Coevery.Tests\Coevery.Framework.Tests.csproj"">
      <Project>{abc826d4-2fa1-4f2f-87de-e6095f653810}</Project>
      <Name>Coevery.Framework.Tests</Name>
    </ProjectReference>
    ");
            
            #line 75 "F:\Shinetech\Coevery-Framework-V1\src\Coevery.Web\Modules\Coevery.CodeGeneration\CodeGenerationTemplates\ModuleTestsCsProj.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CoeveryReferences));
            
            #line default
            #line hidden
            this.Write("\r\n    </ItemGroup>\r\n  <Import Project=\"$(MSBuildToolsPath)\\Microsoft.CSharp.targe" +
                    "ts\" />\r\n</Project>");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "F:\Shinetech\Coevery-Framework-V1\src\Coevery.Web\Modules\Coevery.CodeGeneration\CodeGenerationTemplates\ModuleTestsCsProj.tt"

private global::System.Guid _TestsProjectGuidField;

/// <summary>
/// Access the TestsProjectGuid parameter of the template.
/// </summary>
private global::System.Guid TestsProjectGuid
{
    get
    {
        return this._TestsProjectGuidField;
    }
}

private string _ProjectNameField;

/// <summary>
/// Access the ProjectName parameter of the template.
/// </summary>
private string ProjectName
{
    get
    {
        return this._ProjectNameField;
    }
}

private string _FileIncludesField;

/// <summary>
/// Access the FileIncludes parameter of the template.
/// </summary>
private string FileIncludes
{
    get
    {
        return this._FileIncludesField;
    }
}

private string _CoeveryReferencesField;

/// <summary>
/// Access the CoeveryReferences parameter of the template.
/// </summary>
private string CoeveryReferences
{
    get
    {
        return this._CoeveryReferencesField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool TestsProjectGuidValueAcquired = false;
if (this.Session.ContainsKey("TestsProjectGuid"))
{
    if ((typeof(global::System.Guid).IsAssignableFrom(this.Session["TestsProjectGuid"].GetType()) == false))
    {
        this.Error("The type \'System.Guid\' of the parameter \'TestsProjectGuid\' did not match the type" +
                " of the data passed to the template.");
    }
    else
    {
        this._TestsProjectGuidField = ((global::System.Guid)(this.Session["TestsProjectGuid"]));
        TestsProjectGuidValueAcquired = true;
    }
}
if ((TestsProjectGuidValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("TestsProjectGuid");
    if ((data != null))
    {
        if ((typeof(global::System.Guid).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.Guid\' of the parameter \'TestsProjectGuid\' did not match the type" +
                    " of the data passed to the template.");
        }
        else
        {
            this._TestsProjectGuidField = ((global::System.Guid)(data));
        }
    }
}
bool ProjectNameValueAcquired = false;
if (this.Session.ContainsKey("ProjectName"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["ProjectName"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'ProjectName\' did not match the type of" +
                " the data passed to the template.");
    }
    else
    {
        this._ProjectNameField = ((string)(this.Session["ProjectName"]));
        ProjectNameValueAcquired = true;
    }
}
if ((ProjectNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ProjectName");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'ProjectName\' did not match the type of" +
                    " the data passed to the template.");
        }
        else
        {
            this._ProjectNameField = ((string)(data));
        }
    }
}
bool FileIncludesValueAcquired = false;
if (this.Session.ContainsKey("FileIncludes"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["FileIncludes"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'FileIncludes\' did not match the type o" +
                "f the data passed to the template.");
    }
    else
    {
        this._FileIncludesField = ((string)(this.Session["FileIncludes"]));
        FileIncludesValueAcquired = true;
    }
}
if ((FileIncludesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("FileIncludes");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'FileIncludes\' did not match the type o" +
                    "f the data passed to the template.");
        }
        else
        {
            this._FileIncludesField = ((string)(data));
        }
    }
}
bool CoeveryReferencesValueAcquired = false;
if (this.Session.ContainsKey("CoeveryReferences"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["CoeveryReferences"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'CoeveryReferences\' did not match the t" +
                "ype of the data passed to the template.");
    }
    else
    {
        this._CoeveryReferencesField = ((string)(this.Session["CoeveryReferences"]));
        CoeveryReferencesValueAcquired = true;
    }
}
if ((CoeveryReferencesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("CoeveryReferences");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'CoeveryReferences\' did not match the t" +
                    "ype of the data passed to the template.");
        }
        else
        {
            this._CoeveryReferencesField = ((string)(data));
        }
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class ModuleTestsCsProjBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
